### ISSUE TITLE
keyboard events are displayed on disabled search field

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#84] opened 2015-12-01 21:13 UTC
Even when search field is disabled ({showSearchInputInDropdown: false}) when you open the select box and hit any keyboard key (char) the event is passed to the disabled search field and displayed on screen and search is executed against the values in the select.

When the search field is disabled then all search functionality should be disabled on that input or there should be a way to disable the whole search functionality by a setting.

**Comment by arendjr** [comment] 2015-12-02 13:32
Hm, the search field should be hidden so you shouldn't see anything on-screen. The fact the input is still there and still allows some activity is by design, because otherwise there's no way to catch the arrow keys for navigation in the submenu... But I guess, I simply have never noticed that actual searching is still possible in that case, sounds like an issue indeed.

**Comment by arendjr** [comment] 2015-12-17 14:55
This should be fixed now in master.

**Closed by arendjr** 2015-12-17 14:55 UTC

**Comment by niom** [comment] 2015-12-18 07:07
Works like a charm.

Thank you.
