### ISSUE TITLE
dropdown default positioning bleeds over selectivity element

### ISSUE THREAD

**Issue by niom** [arendjr/selectivity#79] opened 2015-11-27 13:41 UTC
Dropdown does not stick under Selectivity element but bleeds over the element when the dropdown does not fit to the space between the selectivity element and browser window bottom.

This can be tested in https://arendjr.github.io/selectivity/ with the first selectivity selector by placing it near of the browser window bottom. 

Should this kind of functionality be a configuration. e.g. fit-in-browser-space: true/false?

**Comment by arendjr** [comment] 2015-11-27 15:51
This is currently done by design so that the user does not have to scroll. Why exactly would you *not* want this?

**Comment by arendjr** [comment] 2015-11-27 15:54
Btw, the behavior can already be customized by passing a custom `positionDropdown` function with the options. It's not as simple as a boolean option, but allows complete freedom if you like different placement behavior.

**Comment by niom** [comment] 2015-11-27 16:56
It's a matter of ux design and style guides. Even though it's easier to use for the user, it might confuse the user where the actual select box disappeared and it also hides the selected value. 

I might be too used to "standard" select functionality that this design felt odd. 

Thanks from the hint that I can customize the functionality.

**Comment by arendjr** [comment] 2015-11-27 17:01
Cool. I take it I can close this?

Btw, regarding your comment that it hides the selected value, there's also #78 which I intent to fix soon, so hopefully that shouldn't be a concern then anymore either.

Cheers!

**Closed by arendjr** 2015-11-27 17:01 UTC

**Comment by niom** [comment] 2015-11-27 17:19
I would still like to see this as a setting which you could be toggled. So maybe a renaming the issue and tagging it to a feature?

At least then this kind of functionality wouldn't feel odd to old school users ;).

I don't consider this a high priority feature since creating a workaround by overriding the position function isn't that hard.

**Comment by niom** [comment] 2015-12-03 07:01
the replacement was easier than I expected. All I needed to do was to replace positionDropdown with an empty function.

**Comment by arendjr** [comment] 2015-12-03 07:26
Hm, that's interesting :) The default implementation certainly does more than replacement if there isn't sufficient height, though I can understand the default positioning being kinda okay in *some* situations... Isn't the width wrong, for instance?

**Comment by niom** [comment] 2016-02-14 22:31
Yeah, I had to hack it abit more :) 

`````          var width = $selectEl.parent().find('.selectivity-input').outerWidth()
          var selectHeight = $selectEl.height()
          var position = $selectEl.position()
          $el.css({
            left: position.left + 'px',
            top: (position.top + selectHeight) + 'px'
          }).width(width - 2)

`````
